import { useEffect, useRef, useState } from 'react';
import '../styles/pages/legal.css';

const slug = (s) => s.toLowerCase().replace(/&/g, 'and').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

/**
 * Wraps the <section>/<h2> clauses of a legal page as an engineering specification:
 * a document block, a sticky clause index that follows the reader, and CSS-numbered
 * clauses (1, 1.1 ...). The text is untouched; the numbering is generated by CSS counters.
 */
export default function LegalDoc({ doc, rev = 'A', updated, children }) {
  const bodyRef = useRef(null);
  const [items, setItems] = useState([]);
  const [active, setActive] = useState(0);

  useEffect(() => {
    const secs = [...bodyRef.current.querySelectorAll(':scope > section')];
    const list = secs.map((s) => {
      const h = s.querySelector('h2');
      const id = `cl-${slug(h?.textContent || '')}`;
      s.id = id;
      return { id, title: h?.textContent || '' };
    });
    setItems(list);

    const pick = () => {
      const line = window.innerHeight * 0.3;
      let cur = 0;
      secs.forEach((s, i) => { if (s.getBoundingClientRect().top <= line) cur = i; });
      setActive(cur);
    };
    const io = new IntersectionObserver(pick, { rootMargin: '0px 0px -60% 0px', threshold: [0, 1] });
    secs.forEach((s) => io.observe(s));
    window.addEventListener('scroll', pick, { passive: true });
    pick();
    return () => { io.disconnect(); window.removeEventListener('scroll', pick); };
  }, []);

  const go = (e, id) => {
    e.preventDefault();
    document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  };

  return (
    <div className="legal">
      <div className="legal-doc mono">
        <div><span>DOCUMENT</span><b>{doc}</b></div>
        <div><span>REVISION</span><b>{rev}</b></div>
        <div><span>LAST UPDATED</span><b>{updated}</b></div>
        <div><span>CLAUSES</span><b>{String(items.length).padStart(2, '0')}</b></div>
      </div>
      <div className="legal-grid">
        <nav className="legal-idx" aria-label="Clauses">
          <div className="legal-idx-h mono">INDEX</div>
          <ol>
            {items.map((it, i) => (
              <li key={it.id} className={i === active ? 'on' : ''}>
                <a href={`#${it.id}`} onClick={(e) => go(e, it.id)} aria-current={i === active ? 'true' : undefined}>
                  <i className="mono">{String(i + 1).padStart(2, '0')}</i>
                  <span>{it.title}</span>
                </a>
              </li>
            ))}
          </ol>
        </nav>
        <div className="legal-body" ref={bodyRef}>{children}</div>
      </div>
    </div>
  );
}
